package com.institucion.ticketero.module_tickets.domain;

import com.institucion.ticketero.module_executives.domain.Executive;
import com.institucion.ticketero.module_queues.domain.AttentionType;
import com.institucion.ticketero.module_workday.domain.Workday;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Q-Insight: Domain Entity for Ticket.
 * This is the central aggregate root of the ticketing module. It represents a customer's request for service.
 * It holds all information related to a single ticket, including its status, number, and associated customer data.
 * The lifecycle of this entity is managed by the system from creation (RF-001) to closure.
 */
@Entity
@Table(name = "tickets", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ticketNumber", "workday_id"})
})
public class Ticket {

    /**
     * Q-Insight: Primary Key.
     * A unique identifier for the ticket entity.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Q-Insight: Unique Reference Code.
     * A UUID for external reference, as requested in RF-001.
     */
    @Column(unique = true, nullable = false, updatable = false)
    private UUID codigoReferencia;

    /**
     * Q-Insight: Ticket Number.
     * A human-readable, sequential number for the ticket (e.g., "PB-101"). This is generated by the application logic.
     * It's what the customer uses for reference.
     */
    @Column(nullable = false)
    private String ticketNumber;

    /**
     * Q-Insight: Customer Identifier.
     * Stores the customer's RUT/ID. Marked as sensitive data in RNF-005, will require encryption.
     */
    @Column(nullable = false)
    private String nationalId;

    /**
     * Q-Insight: Customer's Phone Number.
     * Used to send notifications (RF-002). This is sensitive personal information.
     */
    @Column
    private String telefono;
    
    /**
     * Q-Insight: Branch Office.
     * The name of the branch office where the ticket was created.
     */
    @Column
    private String branchOffice;

    /**
     * Q-Insight: Position in Queue.
     * The customer's current position in the queue.
     */
    @Column
    private Integer positionInQueue;

    /**
     * Q-Insight: Estimated Wait Time.
     * The estimated wait time in minutes.
     */
    @Column
    private Integer estimatedWaitMinutes;

    /**
     * Q-Insight: Assigned Module Number.
     * The number of the module assigned to the ticket.
     */
    @Column
    private Integer assignedModuleNumber;

    /**
     * Q-Insight: Ticket Status.
     * The current state of the ticket in its lifecycle (PENDING, ATTENDING, etc.).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TicketStatus status;

    /**
     * Q-Insight: Attention Type.
     * The type of queue this ticket belongs to (CAJA, GERENCIA, etc.). This is a foreign key relationship.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AttentionType attentionType;

    /**
     * Q-Insight: Creation Timestamp.
     * The exact time the ticket was created. Used for calculating wait times and for auditing (RF-008).
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Q-Insight: Last Update Timestamp.
     * The time the ticket was last modified.
     */
    private LocalDateTime updatedAt;

    /**
     * Q-Insight: Service Start Timestamp.
     * The time the ticket was assigned to an executive.
     */
    private LocalDateTime attendedAt;

    /**
     * Q-Insight: Service End Timestamp.
     * The time the service was completed and the ticket was closed.
     */
    private LocalDateTime closedAt;

    /**
     * Q-Insight: Assigned Executive.
     * A many-to-one relationship linking the ticket to the executive who is serving or served the customer.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "executive_id")
    private Executive executive;

    /**
     * Q-Insight: Associated Workday.
     * A many-to-one relationship linking the ticket to the workday it belongs to.
     * This forms part of the composite unique key for the ticket number.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "workday_id", nullable = false)
    private Workday workday;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (codigoReferencia == null) {
            codigoReferencia = UUID.randomUUID();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
    
    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getCodigoReferencia() {
        return codigoReferencia;
    }

    public void setCodigoReferencia(UUID codigoReferencia) {
        this.codigoReferencia = codigoReferencia;
    }

    public String getTicketNumber() {
        return ticketNumber;
    }

    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    public String getNationalId() {
        return nationalId;
    }

    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getBranchOffice() {
        return branchOffice;
    }

    public void setBranchOffice(String branchOffice) {
        this.branchOffice = branchOffice;
    }

    public Integer getPositionInQueue() {
        return positionInQueue;
    }

    public void setPositionInQueue(Integer positionInQueue) {
        this.positionInQueue = positionInQueue;
    }

    public Integer getEstimatedWaitMinutes() {
        return estimatedWaitMinutes;
    }

    public void setEstimatedWaitMinutes(Integer estimatedWaitMinutes) {
        this.estimatedWaitMinutes = estimatedWaitMinutes;
    }

    public Integer getAssignedModuleNumber() {
        return assignedModuleNumber;
    }

    public void setAssignedModuleNumber(Integer assignedModuleNumber) {
        this.assignedModuleNumber = assignedModuleNumber;
    }

    public TicketStatus getStatus() {
        return status;
    }

    public void setStatus(TicketStatus status) {
        this.status = status;
    }

    public AttentionType getAttentionType() {
        return attentionType;
    }

    public void setAttentionType(AttentionType attentionType) {
        this.attentionType = attentionType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getAttendedAt() {
        return attendedAt;
    }

    public void setAttendedAt(LocalDateTime attendedAt) {
        this.attendedAt = attendedAt;
    }

    public LocalDateTime getClosedAt() {
        return closedAt;
    }

    public void setClosedAt(LocalDateTime closedAt) {
        this.closedAt = closedAt;
    }

    public Executive getExecutive() {
        return executive;
    }

    public void setExecutive(Executive executive) {
        this.executive = executive;
    }

    public Workday getWorkday() {
        return workday;
    }

    public void setWorkday(Workday workday) {
        this.workday = workday;
    }
}
